name: autopark_appmovil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  provider: ^6.0.0
  firebase_database: ^11.3.4
  intl: ^0.18.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/carro.jpg
    - assets/img/fondito.jpg
    - assets/img/google-logo.png
    - assets/img/fondito.jpg
