// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbNn0HJoa8E7z_OwyPVu4n3W_HIqJKEcg',
    appId: '1:604486127004:web:1dc1da50d4eda341364c59',
    messagingSenderId: '604486127004',
    projectId: 'autopark-2a8b9',
    authDomain: 'autopark-2a8b9.firebaseapp.com',
    storageBucket: 'autopark-2a8b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATp65txvxEOTgyW-RRJ_rHJwM49a_U3R4',
    appId: '1:604486127004:android:d3b0f367fd56f7e4364c59',
    messagingSenderId: '604486127004',
    projectId: 'autopark-2a8b9',
    storageBucket: 'autopark-2a8b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4KxUOGAiwc5MY6UBCn1mduTTiTe4D4o',
    appId: '1:604486127004:ios:d867038591b50f51364c59',
    messagingSenderId: '604486127004',
    projectId: 'autopark-2a8b9',
    storageBucket: 'autopark-2a8b9.firebasestorage.app',
    iosBundleId: 'com.example.autoparkAppmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4KxUOGAiwc5MY6UBCn1mduTTiTe4D4o',
    appId: '1:604486127004:ios:3236b5b864736601364c59',
    messagingSenderId: '604486127004',
    projectId: 'autopark-2a8b9',
    storageBucket: 'autopark-2a8b9.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbNn0HJoa8E7z_OwyPVu4n3W_HIqJKEcg',
    appId: '1:604486127004:web:f429fe8cbcbc71a2364c59',
    messagingSenderId: '604486127004',
    projectId: 'autopark-2a8b9',
    authDomain: 'autopark-2a8b9.firebaseapp.com',
    storageBucket: 'autopark-2a8b9.firebasestorage.app',
  );
}
